"""rename node_heartbeats.metadata to metadata_

Revision ID: a00f7990d102
Revises: b1c2d3e4f5a6
Create Date: 2025-08-31 18:34:49.046051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00f7990d102'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('owner_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index(op.f('ix_datasets_owner_address'), 'datasets', ['owner_address'], unique=False)
    op.create_table('marketplace_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('provider_address', sa.String(), nullable=True),
    sa.Column('price_per_hour', sa.Float(), nullable=False),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('min_rental_hours', sa.Integer(), nullable=True),
    sa.Column('max_rental_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_listings_machine_id'), 'marketplace_listings', ['machine_id'], unique=True)
    op.create_index(op.f('ix_marketplace_listings_provider_address'), 'marketplace_listings', ['provider_address'], unique=False)
    op.create_table('node_heartbeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_heartbeats_machine_id'), 'node_heartbeats', ['machine_id'], unique=False)
    op.create_table('node_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_logs_machine_id'), 'node_logs', ['machine_id'], unique=False)
    op.create_table('rental_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('renter_address', sa.String(), nullable=True),
    sa.Column('provider_address', sa.String(), nullable=True),
    sa.Column('hours_rented', sa.Integer(), nullable=False),
    sa.Column('price_per_hour', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('rental_start', sa.DateTime(), nullable=True),
    sa.Column('rental_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_history_machine_id'), 'rental_history', ['machine_id'], unique=False)
    op.create_index(op.f('ix_rental_history_provider_address'), 'rental_history', ['provider_address'], unique=False)
    op.create_index(op.f('ix_rental_history_renter_address'), 'rental_history', ['renter_address'], unique=False)
    op.create_table('dataset_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user_address', sa.String(), nullable=True),
    sa.Column('reward_amount', sa.Float(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_usage_dataset_id'), 'dataset_usage', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_usage_user_address'), 'dataset_usage', ['user_address'], unique=False)
    op.add_column('provider_machines', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('provider_machines', sa.Column('status', sa.String(), nullable=True))
    op.add_column('provider_machines', sa.Column('metrics', sa.JSON(), nullable=True))
    op.add_column('provider_machines', sa.Column('price_per_hour_wei', sa.String(), nullable=True))
    op.add_column('provider_machines', sa.Column('listed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_machines', 'listed')
    op.drop_column('provider_machines', 'price_per_hour_wei')
    op.drop_column('provider_machines', 'metrics')
    op.drop_column('provider_machines', 'status')
    op.drop_column('provider_machines', 'last_seen')
    op.drop_index(op.f('ix_dataset_usage_user_address'), table_name='dataset_usage')
    op.drop_index(op.f('ix_dataset_usage_dataset_id'), table_name='dataset_usage')
    op.drop_table('dataset_usage')
    op.drop_index(op.f('ix_rental_history_renter_address'), table_name='rental_history')
    op.drop_index(op.f('ix_rental_history_provider_address'), table_name='rental_history')
    op.drop_index(op.f('ix_rental_history_machine_id'), table_name='rental_history')
    op.drop_table('rental_history')
    op.drop_index(op.f('ix_node_logs_machine_id'), table_name='node_logs')
    op.drop_table('node_logs')
    op.drop_index(op.f('ix_node_heartbeats_machine_id'), table_name='node_heartbeats')
    op.drop_table('node_heartbeats')
    op.drop_index(op.f('ix_marketplace_listings_provider_address'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_machine_id'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_datasets_owner_address'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
